# Generated by Django 5.1.3 on 2025-02-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_accounttype_stk_passkey_stktransaction_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttype',
            old_name='b2c_initiator',
            new_name='b2c_securitycredential',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='b2c_security',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='b2ctransaction',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='b2ctransaction',
            name='transaction_time',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='b2c_commandid',
            field=models.CharField(choices=[('SalaryPayment', 'SalaryPayment'), ('BusinessPayment', 'BusinessPayment'), ('PromotionPayment', 'PromotionPayment')], default='BusinessPayToBulk', max_length=255),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='b2c_initiatorname',
            field=models.CharField(blank=True, help_text='your user name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='b2c_payment_remark',
            field=models.CharField(blank=True, default='Payment Ok', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='business_description',
            field=models.CharField(blank=True, default='STK Push', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='business_name',
            field=models.CharField(blank=True, help_text='This Is the name of the business', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='c2b_responsetype',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Completed', max_length=225),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='transactiontype',
            field=models.CharField(choices=[('CustomerBuyGoodsOnline', 'CustomerBuyGoodsOnline'), ('CustomerPayBillOnline', 'CustomerPayBillOnline')], default='CustomerPayBillOnline', max_length=225),
        ),
        migrations.AddField(
            model_name='b2ctransaction',
            name='charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='b2ctransaction',
            name='completed_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='b2ctransaction',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='b2ctransaction',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='business',
            field=models.CharField(blank=True, help_text='This Is the name of the business', max_length=255),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='b2c_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b2ctransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='b2ctransaction',
            name='originator_conversation_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b2ctransaction',
            name='result_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b2ctransaction',
            name='result_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b2ctransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
