# Generated by Django 5.1.3 on 2025-02-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_b2c_initiator_accounttype_b2c_securitycredential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='b2c_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='b2c_commandid',
            field=models.CharField(choices=[('BusinessPayment', 'BusinessPayment'), ('SalaryPayment', 'SalaryPayment'), ('PromotionPayment', 'PromotionPayment')], default='BusinessPayToBulk', max_length=255),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='transactiontype',
            field=models.CharField(choices=[('CustomerPayBillOnline', 'CustomerPayBillOnline'), ('CustomerBuyGoodsOnline', 'CustomerBuyGoodsOnline')], default='CustomerPayBillOnline', max_length=225),
        ),
    ]
