# Generated by Django 5.1.3 on 2025-02-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_accounttype_b2c_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='b2c_commandid',
            field=models.CharField(choices=[('PromotionPayment', 'PromotionPayment'), ('SalaryPayment', 'SalaryPayment'), ('BusinessPayment', 'BusinessPayment')], default='BusinessPayToBulk', max_length=255),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='c2b_responsetype',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=225),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='transactiontype',
            field=models.CharField(choices=[('CustomerBuyGoodsOnline', 'CustomerBuyGoodsOnline'), ('CustomerPayBillOnline', 'CustomerPayBillOnline')], default='CustomerPayBillOnline', max_length=225),
        ),
    ]
