# Generated by Django 5.1.3 on 2025-02-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_accounttype_b2c_commandid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='b2c_commandid',
            field=models.CharField(choices=[('BusinessPayment', 'BusinessPayment'), ('PromotionPayment', 'PromotionPayment'), ('SalaryPayment', 'SalaryPayment')], default='BusinessPayment', max_length=255),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='transactiontype',
            field=models.CharField(choices=[('CustomerPayBillOnline', 'CustomerPayBillOnline'), ('CustomerBuyGoodsOnline', 'CustomerBuyGoodsOnline')], default='CustomerPayBillOnline', max_length=225),
        ),
    ]
